import React from 'react';
import { MatchAnalysis } from '../types';
import { TemplateStyle } from '../constants';

interface KSCResponsesViewProps {
  analysis: MatchAnalysis;
  template: TemplateStyle;
}

export const KSCResponsesView: React.FC<KSCResponsesViewProps> = ({ analysis, template }) => {
  if (!analysis.KSC_Responses_Drafts || analysis.KSC_Responses_Drafts.length === 0) {
    return (
      <div className="bg-white p-10 shadow-lg max-w-4xl mx-auto text-center text-[var(--sys-color-worker-ash-base)] italic">
        No Key Selection Criteria responses generated for this role.
      </div>
    );
  }

  return (
    <div 
      className="bg-white p-10 shadow-lg max-w-4xl mx-auto"
      style={{ 
        fontFamily: template.fontSans,
        color: template.textColor,
        lineHeight: '1.6'
      }}
    >
      <div 
        className="text-center mb-10 border-b-2 pb-6"
        style={{ borderColor: template.primaryColor }}
      >
        <h1 
          className="text-3xl font-bold uppercase tracking-tight mb-2"
          style={{ color: template.primaryColor }}
        >
          Key Selection Criteria Responses
        </h1>
        <p className="text-sm opacity-70 italic">Tailored for your application</p>
      </div>

      <div className="space-y-12">
        {analysis.KSC_Responses_Drafts.map((ksc, i) => (
          <div key={i} className="animate-fade-in">
            <h2 
              className="text-lg font-bold mb-4 pb-2 border-b"
              style={{ 
                color: template.headingColor, 
                borderColor: template.borderColor,
                fontFamily: template.fontSerif 
              }}
            >
              Criterion {i + 1}: {ksc.KSC_Prompt}
            </h2>
            <div className="text-sm space-y-4 whitespace-pre-wrap">
              {ksc.Response}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-12 pt-6 border-t text-[10px] opacity-40 text-center uppercase tracking-widest">
        Generated by CareerCopilot AI • STAR Method Optimized
      </div>
    </div>
  );
};
